export type PhotoCategory = "street" | "plants" | "city" | "other";
export type PhotoOrientation = "portrait" | "landscape" | "square";

export interface Photo {
  id: string;
  src: string;
  alt: string;
  category: PhotoCategory;
  orientation: PhotoOrientation;
  /** width in px (used for masonry aspect ratio) */
  width: number;
  /** height in px (used for masonry aspect ratio) */
  height: number;
  location?: string;
  date?: string;
  caption?: string;
  exif?: {
    camera?: string;
    lens?: string;
    iso?: string;
    aperture?: string;
    shutter?: string;
  };
}

export const categoryMeta: Record<
  PhotoCategory,
  { label: string; accent: string; accentBorder: string; accentText: string; accentBg: string }
> = {
  street: {
    label: "Street",
    accent: "#f59e0b",
    accentBorder: "border-amber-400/40",
    accentText: "text-amber-400",
    accentBg: "bg-amber-400/10",
  },
  plants: {
    label: "Plants",
    accent: "#34d399",
    accentBorder: "border-emerald-400/40",
    accentText: "text-emerald-400",
    accentBg: "bg-emerald-400/10",
  },
  city: {
    label: "City",
    accent: "#60a5fa",
    accentBorder: "border-blue-400/40",
    accentText: "text-blue-400",
    accentBg: "bg-blue-400/10",
  },
  other: {
    label: "Other",
    accent: "#c77dff",
    accentBorder: "border-neon-lavender/40",
    accentText: "text-neon-lavender",
    accentBg: "bg-neon-lavender/10",
  },
};

export const categories = Object.keys(categoryMeta) as PhotoCategory[];

// ──────────────────────────────────────────────────────────────
// Add your photos here. Place image files in public/img/gallery/
// and reference them as "/img/gallery/filename.webp".
//
// Example:
// {
//   id: "street-001",
//   src: "/img/gallery/street/rainy-alley.webp",
//   alt: "Reflections on a rainy Amsterdam alley",
//   category: "street",
//   orientation: "portrait",
//   width: 1200,
//   height: 1800,
//   location: "Amsterdam, NL",
//   date: "2026-05",
//   caption: "after the rain, the city exhales",
//   exif: { camera: "Fujifilm X-T5", lens: "23mm f/2", iso: "800", aperture: "f/2", shutter: "1/125s" },
// },
// ──────────────────────────────────────────────────────────────

export const photos: Photo[] = [
  {
    id: "12061",
    src: "/img/gallery/12061.jpg",
    alt: "Gallery Image 12061",
    category: "other",
    orientation: "portrait",
    width: 4000,
    height: 6000,
  },
  {
    id: "arad-1-2",
    src: "/img/gallery/arad-1-2.jpg",
    alt: "Gallery Image arad-1-2",
    category: "other",
    orientation: "portrait",
    width: 4000,
    height: 6000,
  },
  {
    id: "bucuresti_edited_mlempeg-1",
    src: "/img/gallery/bucuresti_edited_mlempeg-1.jpg",
    alt: "Gallery Image bucuresti_edited_mlempeg-1",
    category: "other",
    orientation: "portrait",
    width: 3919,
    height: 5563,
  },
  {
    id: "DSC00248-Enhanced-NR-4",
    src: "/img/gallery/DSC00248-Enhanced-NR-4.jpg",
    alt: "Gallery Image DSC00248-Enhanced-NR-4",
    category: "other",
    orientation: "landscape",
    width: 5949,
    height: 3966,
  },
  {
    id: "DSC00271-4",
    src: "/img/gallery/DSC00271-4.jpg",
    alt: "Gallery Image DSC00271-4",
    category: "other",
    orientation: "portrait",
    width: 3051,
    height: 4577,
  },
  {
    id: "DSC00659-Enhanced-NR-4",
    src: "/img/gallery/DSC00659-Enhanced-NR-4.jpg",
    alt: "Gallery Image DSC00659-Enhanced-NR-4",
    category: "other",
    orientation: "portrait",
    width: 3943,
    height: 5728,
  },
  {
    id: "DSC00777-4",
    src: "/img/gallery/DSC00777-4.jpg",
    alt: "Gallery Image DSC00777-4",
    category: "other",
    orientation: "portrait",
    width: 4000,
    height: 6000,
  },
  {
    id: "DSC00944-Enhanced-NR-4",
    src: "/img/gallery/DSC00944-Enhanced-NR-4.jpg",
    alt: "Gallery Image DSC00944-Enhanced-NR-4",
    category: "other",
    orientation: "landscape",
    width: 5806,
    height: 3871,
  },
  {
    id: "DSC01027-Enhanced-NR-4",
    src: "/img/gallery/DSC01027-Enhanced-NR-4.jpg",
    alt: "Gallery Image DSC01027-Enhanced-NR-4",
    category: "other",
    orientation: "portrait",
    width: 3720,
    height: 5580,
  },
  {
    id: "DSC01050-Enhanced-NR-4",
    src: "/img/gallery/DSC01050-Enhanced-NR-4.jpg",
    alt: "Gallery Image DSC01050-Enhanced-NR-4",
    category: "other",
    orientation: "portrait",
    width: 3601,
    height: 5402,
  },
  {
    id: "DSC01086-Enhanced-NR-4",
    src: "/img/gallery/DSC01086-Enhanced-NR-4.jpg",
    alt: "Gallery Image DSC01086-Enhanced-NR-4",
    category: "other",
    orientation: "landscape",
    width: 6000,
    height: 4000,
  },
  {
    id: "DSC01170-Enhanced-NR-4",
    src: "/img/gallery/DSC01170-Enhanced-NR-4.jpg",
    alt: "Gallery Image DSC01170-Enhanced-NR-4",
    category: "other",
    orientation: "portrait",
    width: 3946,
    height: 5919,
  },
  {
    id: "DSC01265-24",
    src: "/img/gallery/DSC01265-24.jpg",
    alt: "Gallery Image DSC01265-24",
    category: "other",
    orientation: "portrait",
    width: 3666,
    height: 5499,
  },
  {
    id: "DSC01307-Enhanced-NR",
    src: "/img/gallery/DSC01307-Enhanced-NR.jpg",
    alt: "Gallery Image DSC01307-Enhanced-NR",
    category: "other",
    orientation: "portrait",
    width: 4000,
    height: 6000,
  },
  {
    id: "DSC01318",
    src: "/img/gallery/DSC01318.jpg",
    alt: "Gallery Image DSC01318",
    category: "other",
    orientation: "portrait",
    width: 4000,
    height: 6000,
  },
  {
    id: "DSC05427-Enhanced-NR",
    src: "/img/gallery/DSC05427-Enhanced-NR.jpg",
    alt: "Gallery Image DSC05427-Enhanced-NR",
    category: "other",
    orientation: "portrait",
    width: 3606,
    height: 5409,
  },
  {
    id: "DSC05731",
    src: "/img/gallery/DSC05731.jpg",
    alt: "Gallery Image DSC05731",
    category: "other",
    orientation: "portrait",
    width: 4000,
    height: 6000,
  },
  {
    id: "DSC05993",
    src: "/img/gallery/DSC05993.jpg",
    alt: "Gallery Image DSC05993",
    category: "other",
    orientation: "portrait",
    width: 3927,
    height: 5890,
  },
  {
    id: "DSC06070",
    src: "/img/gallery/DSC06070.jpg",
    alt: "Gallery Image DSC06070",
    category: "other",
    orientation: "portrait",
    width: 4000,
    height: 6000,
  },
  {
    id: "DSC06141",
    src: "/img/gallery/DSC06141.jpg",
    alt: "Gallery Image DSC06141",
    category: "other",
    orientation: "portrait",
    width: 4000,
    height: 6000,
  },
  {
    id: "DSC06221",
    src: "/img/gallery/DSC06221.jpg",
    alt: "Gallery Image DSC06221",
    category: "other",
    orientation: "portrait",
    width: 3906,
    height: 5859,
  },
  {
    id: "DSC06559",
    src: "/img/gallery/DSC06559.jpg",
    alt: "Gallery Image DSC06559",
    category: "other",
    orientation: "portrait",
    width: 4000,
    height: 6000,
  },
  {
    id: "DSC06561",
    src: "/img/gallery/DSC06561.jpg",
    alt: "Gallery Image DSC06561",
    category: "other",
    orientation: "portrait",
    width: 3593,
    height: 5389,
  },
  {
    id: "DSC06570",
    src: "/img/gallery/DSC06570.jpg",
    alt: "Gallery Image DSC06570",
    category: "other",
    orientation: "portrait",
    width: 4000,
    height: 6000,
  },
  {
    id: "DSC06573",
    src: "/img/gallery/DSC06573.jpg",
    alt: "Gallery Image DSC06573",
    category: "other",
    orientation: "portrait",
    width: 2667,
    height: 4000,
  },
  {
    id: "DSC06581",
    src: "/img/gallery/DSC06581.jpg",
    alt: "Gallery Image DSC06581",
    category: "other",
    orientation: "portrait",
    width: 4000,
    height: 6000,
  },
  {
    id: "DSC06584",
    src: "/img/gallery/DSC06584.jpg",
    alt: "Gallery Image DSC06584",
    category: "other",
    orientation: "portrait",
    width: 4000,
    height: 6000,
  },
  {
    id: "DSC06601",
    src: "/img/gallery/DSC06601.jpg",
    alt: "Gallery Image DSC06601",
    category: "other",
    orientation: "portrait",
    width: 4000,
    height: 6000,
  },
  {
    id: "DSC06602",
    src: "/img/gallery/DSC06602.jpg",
    alt: "Gallery Image DSC06602",
    category: "other",
    orientation: "portrait",
    width: 4000,
    height: 6000,
  },
  {
    id: "DSC06614",
    src: "/img/gallery/DSC06614.jpg",
    alt: "Gallery Image DSC06614",
    category: "other",
    orientation: "portrait",
    width: 3525,
    height: 5287,
  },
  {
    id: "DSC06634",
    src: "/img/gallery/DSC06634.jpg",
    alt: "Gallery Image DSC06634",
    category: "other",
    orientation: "portrait",
    width: 4000,
    height: 6000,
  },
  {
    id: "DSC06640",
    src: "/img/gallery/DSC06640.jpg",
    alt: "Gallery Image DSC06640",
    category: "other",
    orientation: "portrait",
    width: 4000,
    height: 6000,
  },
  {
    id: "DSC06656",
    src: "/img/gallery/DSC06656.jpg",
    alt: "Gallery Image DSC06656",
    category: "other",
    orientation: "portrait",
    width: 4000,
    height: 6000,
  },
  {
    id: "DSC06661",
    src: "/img/gallery/DSC06661.jpg",
    alt: "Gallery Image DSC06661",
    category: "other",
    orientation: "portrait",
    width: 4000,
    height: 6000,
  },
  {
    id: "DSC06668",
    src: "/img/gallery/DSC06668.jpg",
    alt: "Gallery Image DSC06668",
    category: "other",
    orientation: "portrait",
    width: 4000,
    height: 6000,
  },
  {
    id: "DSC07219-1",
    src: "/img/gallery/DSC07219-1.jpg",
    alt: "Gallery Image DSC07219-1",
    category: "other",
    orientation: "portrait",
    width: 4000,
    height: 4974,
  },
  {
    id: "DSC09310-1",
    src: "/img/gallery/DSC09310-1.jpg",
    alt: "Gallery Image DSC09310-1",
    category: "other",
    orientation: "portrait",
    width: 4000,
    height: 6000,
  },
  {
    id: "DSC09452-1",
    src: "/img/gallery/DSC09452-1.jpg",
    alt: "Gallery Image DSC09452-1",
    category: "other",
    orientation: "landscape",
    width: 6000,
    height: 4000,
  },
  {
    id: "DSC09986",
    src: "/img/gallery/DSC09986.jpg",
    alt: "Gallery Image DSC09986",
    category: "other",
    orientation: "portrait",
    width: 4024,
    height: 6024,
  },
  {
    id: "sakura-287",
    src: "/img/gallery/sakura-287.jpg",
    alt: "Gallery Image sakura-287",
    category: "other",
    orientation: "portrait",
    width: 4000,
    height: 6000,
  },
  {
    id: "IMG_0004",
    src: "/img/gallery/IMG_0004.JPG",
    alt: "Gallery Image IMG_0004",
    category: "other",
    orientation: "portrait",
    width: 4000,
    height: 6000,
  },
  {
    id: "IMG_1408",
    src: "/img/gallery/IMG_1408.JPG",
    alt: "Gallery Image IMG_1408",
    category: "other",
    orientation: "portrait",
    width: 3879,
    height: 5818,
  },
  {
    id: "TIMISOARA-127",
    src: "/img/gallery/TIMISOARA-127.JPG",
    alt: "Gallery Image TIMISOARA-127",
    category: "other",
    orientation: "portrait",
    width: 3945,
    height: 5918,
  },
  {
    id: "DSC00086-4",
    src: "/img/gallery/DSC00086-4.jpeg",
    alt: "Gallery Image DSC00086-4",
    category: "other",
    orientation: "portrait",
    width: 4000,
    height: 6000,
  },
  {
    id: "cat",
    src: "/img/gallery/cat.JPEG",
    alt: "Gallery Image cat",
    category: "other",
    orientation: "portrait",
    width: 4024,
    height: 6026,
  },
  {
    id: "DSC03355",
    src: "/img/gallery/DSC03355.JPEG",
    alt: "Gallery Image DSC03355",
    category: "other",
    orientation: "landscape",
    width: 6026,
    height: 4024,
  },
  {
    id: "DSC03376",
    src: "/img/gallery/DSC03376.JPEG",
    alt: "Gallery Image DSC03376",
    category: "other",
    orientation: "portrait",
    width: 4024,
    height: 6026,
  },
  {
    id: "DSC05320",
    src: "/img/gallery/DSC05320.JPEG",
    alt: "Gallery Image DSC05320",
    category: "other",
    orientation: "portrait",
    width: 3510,
    height: 5637,
  },
  {
    id: "DSC05870-Enhanced-NR",
    src: "/img/gallery/DSC05870-Enhanced-NR.JPEG",
    alt: "Gallery Image DSC05870-Enhanced-NR",
    category: "other",
    orientation: "portrait",
    width: 4000,
    height: 6000,
  },
  {
    id: "DSC05979",
    src: "/img/gallery/DSC05979.JPEG",
    alt: "Gallery Image DSC05979",
    category: "other",
    orientation: "landscape",
    width: 5861,
    height: 3907,
  },
  {
    id: "IMG_0001",
    src: "/img/gallery/IMG_0001.JPEG",
    alt: "Gallery Image IMG_0001",
    category: "other",
    orientation: "portrait",
    width: 4000,
    height: 6000,
  },
  {
    id: "mountain",
    src: "/img/gallery/mountain.JPEG",
    alt: "Gallery Image mountain",
    category: "other",
    orientation: "landscape",
    width: 6026,
    height: 4024,
  },
];
